### ISSUE TITLE
安卓版本无法正常使用

### ISSUE THREAD

**Issue by Takana3** [COMEIX/Colorify#1]
在安卓13的一加ace2上使用release中v3.1.1的安装包，安装后实际版本号为3.0.0。在使用时，界面UI与 [BV1qM41197LZ](https://www.bilibili.com/video/BV1qM41197LZ) 这条视频中的不一样，在使用粒子画和像素画时无法调起图片选择，点击打包后就没有然后了。
如果是我的使用方法错误的话，还请告诉我正确的使用方法🥹

**Comment by COMEIX** [comment]
- 标注版本号与实际APP版本号不同的情况是疏忽，我马上会解决。
- BV1qM41197LZ 中的是此APP的前身Functior，版本号是v2.x，现Functior的仓库已被删除。
- 点击生成后没有调起图片选择是已知的鸿蒙系统会有的问题，一加手机还没有先例，我后续会跟进调查。
    - (实际上，这大概率是Flutter SDK经过某个更新后产生的Bug)
- 您可以先通过以下步骤进行一个初步的错误排除：
    - 输入的参数是否合法，可以尝试重新打开APP并在不修改任何参数的情况下尝试生成
    - 检查是否给予了本APP对外部存储的读写权限
        - 对于Android 13以前的版本，包括READ_EXTERNAL_STORAGE与WRITE_EXTERNAL_STORAGE两个权限
        - 对于Android 13及以后的版本，为MANAGE_EXTERNAL_STORAGE权限
- 我正在开发全新的版本，底层代码全部会经重写，所以此版本我大概率不会再维护。

**Comment by Takana3** [comment]
开启了 MANAGE_EXTERNAL_STORAGE 权限，在不修改任何参数下依旧无法生成🥹
那我还是等你的新版本吧🌹
